POST http://localhost:8080/accounts
Content-Type: application/json


{
    "username" : "honeycarbs",
    "email" : "honeycarbs@honeycarbs.com",
    "password": "qwerty123",
    "user" : { 
        "age": 21
    ,
        "race" : "white",
        "gender": "F" 
    },
    "locations" : [
        {
            "name"     : "Москва",
            "region"   : "Москва",
            "district" : "Центральный"
        },
        {
            "name"     : "Санкт-Петербург",
            "region"   : "Санкт-Петербург",
            "district" : "Северо-Западный"
        },
        {
            "name"     : "Калининград",
            "region"   : "Калининградская область",
            "district" : "Северо-Западный"
        }
    ],
    "education_place": [
        {
            "name": "Московский государственный технический университет им. Н. Э. Баумана",
            "education_program": {
                "field": "Техническое",
                "level": "Бакалавриат"
            }
            
        }
    ]
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "username" : "moderator",
    "email" : "moderator@moderator.com",
    "password": "moderator",
    "user" : { 
        "age": 21
    ,
        "race" : "white",
        "gender": "M" 
    },
    "locations" : [
    ],
    "education_place": [
    ]
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "username" : "gopher",
    "email" : "gopher@gopher.com",
    "password": "qwerty123",
    "user" : { 
        "age": 20
    ,
        "race" : "white",
        "gender": "M" 
    },
    "locations" : [
        {
            "name"     : "Москва",
            "region"   : "Москва",
            "district" : "Центральный"
        }
    ],
    "education_place": [
        {
            "name": "Московский государственный технический университет им. Н. Э. Баумана",
            "education_program": {
                "field": "Техническое",
                "level": "Бакалавриат"
            }
            
        }
    ]
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "username" : "admin",
    "email" : "admin@admin.com",
    "password": "adminadmin",
    "user" : { 
        "age": 21
    ,
        "race" : "white",
        "gender": "M" 
    },
    "locations" : [
    ],
    "education_place": [
    ]
}

###

POST http://localhost:8080/sessions
Content-Type: application/json
Origin: "google.com"

{
    "username" : "honeycarbs",
    "email" : "honeycarbs@honeycarbs.com",
    "password": "qwerty123"
}

###

POST http://localhost:8080/sessions
Content-Type: application/json
Origin: "google.com"

{
    "username" : "gopher",
    "email" : "gopher@gopher.com",
    "password": "qwerty123"
}

###

POST http://localhost:8080/sessions
Content-Type: application/json
Origin: "google.com"

{
    "username" : "moderator",
    "email" : "moderator@moderator.com",
    "password": "moderator"
}

###

POST http://localhost:8080/sessions
Content-Type: application/json
Origin: "google.com"

{
    "username" : "admin",
    "email" : "admin@admin.com",
    "password": "adminadmin"
}

###
GET http://localhost:8080/moderate/accounts
Content-Type: application/json

###
GET http://localhost:8080/administrate/stats
Content-Type: application/json


###
GET http://localhost:8080/authorized/whoami
Content-Type: application/json

###
GET  http://localhost:8080/locations
Origin: "google.com"
Content-Type: application/json

###
GET  http://localhost:8080/education
Content-Type: application/json

###

POST http://localhost:8080/authorized/poll
Content-Type: application/json

{
	"poll": [
		{ 
            "word": "ужасающий",
            "mark": 1
            
        },
        {
            "word": "ужасный",
            "mark": 1
            
        },
        {
            "word": "страшный",
            "mark": 1
        },
        {
            "word": "чудовищный",
            "mark": 1
        },
        {
            "word": "тошнотворный",
            "mark": 1
        },
        {
            "word": "очень плохой",
            "mark": 1
        },
        {
            "word": "действительно плохой",
            "mark": 1
        },
        {
            "word": "дрянной",
            "mark": 1
        },
        {
            "word": "неудовлетворительный",
            "mark": 1
        },
        {
            "word": "плохой",
            "mark": 1
        },
        {
            "word": "слабый",
            "mark": 1
        },
        {
            "word": "в большей степени плохой",
            "mark": 1
        },
        {
            "word": "довольной плохой",
            "mark": 1
        },
        {
            "word": "плоховатый",
            "mark": 1
        },
        {
            "word": "ниже среднего",
            "mark": 1
        },
        {
            "word": "посредственный",
            "mark": 1
        },
        {
            "word": "обычный",
            "mark": 1
        },
        {
            "word": "неплохой",
            "mark": 1
        },
        {
            "word": "приличный",
            "mark": 1
        },
        {
            "word": "вполне удовлетворительный",
            "mark": 1
        },
        {
            "word": "ок",
            "mark": 1
        },
        {
            "word": "удовлетворительный",
            "mark": 1
        },
        {
            "word": "достаточно хороший",
            "mark": 1
        },
        {
            "word": "недурный",
            "mark": 1
        },
        {
            "word": "в большей степени хороший",
            "mark": 1
        },
        {
            "word": "нормальный",
            "mark": 1
        },
        {
            "word": "выше среднего",
            "mark": 1
        },
        {
            "word": "довольно хороший",
            "mark": 1
        },
        {
            "word": "хороший",
            "mark": 1
        },
        {
            "word": "отличный",
            "mark": 1
        },
        {
            "word": "действительно хороший",
            "mark": 1
        },
        {
            "word": "очень хороший",
            "mark": 1
        },
        {
            "word": "великолепный",
            "mark": 1
        },
        {
            "word": "изумительный",
            "mark": 1
        },
        {
            "word": "невероятный",
            "mark": 1
        },
        {
            "word": "блестящий",
            "mark": 1
        },
        {
            "word": "экстраординарный",
            "mark": 1
        },
        {
            "word": "превосходный",
            "mark": 1
        },
        {
            "word": "выдающийся",
            "mark": 1
        },
        {
            "word": "идеальный",
            "mark": 1
        }
	]
}

###

POST http://localhost:8080/authorized/poll
Content-Type: application/json

{
	"poll": [
		{ 
            "word": "ужасающий",
            "mark": 1
            
        },
        {
            "word": "ужасный",
            "mark": 2
            
        },
        {
            "word": "страшный",
            "mark": 1
        },
        {
            "word": "чудовищный",
            "mark": 1
        },
        {
            "word": "тошнотворный",
            "mark": 1
        },
        {
            "word": "очень плохой",
            "mark": 4
        },
        {
            "word": "действительно плохой",
            "mark": 5
        },
        {
            "word": "дрянной",
            "mark": 1
        },
        {
            "word": "неудовлетворительный",
            "mark": 1
        },
        {
            "word": "плохой",
            "mark": 1
        },
        {
            "word": "слабый",
            "mark": 1
        },
        {
            "word": "в большей степени плохой",
            "mark": 1
        },
        {
            "word": "довольной плохой",
            "mark": 1
        },
        {
            "word": "плоховатый",
            "mark": 1
        },
        {
            "word": "ниже среднего",
            "mark": 1
        },
        {
            "word": "посредственный",
            "mark": 1
        },
        {
            "word": "обычный",
            "mark": 1
        },
        {
            "word": "неплохой",
            "mark": 1
        },
        {
            "word": "приличный",
            "mark": 1
        },
        {
            "word": "вполне удовлетворительный",
            "mark": 9
        },
        {
            "word": "ок",
            "mark": 1
        },
        {
            "word": "удовлетворительный",
            "mark": 1
        },
        {
            "word": "достаточно хороший",
            "mark": 1
        },
        {
            "word": "недурный",
            "mark": 1
        },
        {
            "word": "в большей степени хороший",
            "mark": 7
        },
        {
            "word": "нормальный",
            "mark": 1
        },
        {
            "word": "выше среднего",
            "mark": 1
        },
        {
            "word": "довольно хороший",
            "mark": 1
        },
        {
            "word": "хороший",
            "mark": 1
        },
        {
            "word": "отличный",
            "mark": 1
        },
        {
            "word": "действительно хороший",
            "mark": 1
        },
        {
            "word": "очень хороший",
            "mark": 1
        },
        {
            "word": "великолепный",
            "mark": 1
        },
        {
            "word": "изумительный",
            "mark": 2
        },
        {
            "word": "невероятный",
            "mark": 1
        },
        {
            "word": "блестящий",
            "mark": 1
        },
        {
            "word": "экстраординарный",
            "mark": 1
        },
        {
            "word": "превосходный",
            "mark": 1
        },
        {
            "word": "выдающийся",
            "mark": 1
        },
        {
            "word": "идеальный",
            "mark": 1
        }
	]
}

###

GET  http://localhost:8080/authorized/poll
Content-Type: application/json

###

GET  http://localhost:8080/authorized/results
Content-Type: application/json